spring.application.name=SpringBootExpert_LibaryApi

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//140.238.179.244:1521/orcl.subnet01201509.vcn01201509.oraclevcn.com
spring.datasource.username=JJ
spring.datasource.password=tecsis

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql: true
