spring.application.name=SpringBootExpert_LibaryApi
spring.profiles.active=production
# Variavel de ambiente - SPRING_PROFILES_ACTIVE=production
spring.output.ansi.enabled=ALWAYS

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER:JJ}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}

springdoc.override-with-generic-response=false

#logging.file.name=app.log
logging.level.root=warn
logging.level.com.github.joseprandj=trace
logging.level.org.springframework.web=debug
logging.level.org.springframework.security=trace
# Cada nível de erro baixo herda o seu anterior
# trace - Level com mais detalhes de rastreamento da aplicação
# debug - Informação de depuração de fluxos e variáveis em execução
# info - Informações gerais da aplicação
# warn - Eventos potencialmente problemáticos
# erro - Erros que impedem operação específica

logging.pattern.console=%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n

management.server.port=9090
management.endpoints.web.exposure.include=*